spring:
#  redis:
#    database: 0    #数据库默认索引
#    hostName: 192.168.31.113
#    port: 6379
#    password: 123987       # 密码（默认为空）
#    timeout: 6000  # 连接超时时长（毫秒）
#    jedis:
#        pool:
#            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#            max-idle: 10      # 连接池中的最大空闲连接
#            min-idle: 5
  jedis:
    pool:
      host: 127.0.0.1
      port: 6379
      password: 123987
      config:
        maxTotal: 100
        maxIdle: 10
        maxWaitMillis: 100000
  datasource:
    #此处配置需要的数据源
    username: root
    #      username: root
    password: msjkj2019
    #      password: root
    #      url: jdbc:oracle:thin:@172.16.10.66:1521:orcl
    url: jdbc:mysql://118.190.208.221:3306/msjgoods?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #     driver-class-name: oracle.jdbc.OracleDriver
    driver-class-name: com.mysql.jdbc.Driver
    # 从库数据源
    slave:
      # 从数据源开关/默认关闭
      enabled: false
      url:
      username:
      password:
  # 初始连接数
  initial-size: 10
  # 最大连接池数量
  max-active: 100
  # 最小连接池数量
  min-idle: 10
  # 配置获取连接等待超时的时间
  max-wait: 60000
  # 打开PSCache，并且指定每个连接上PSCache的大小
  pool-prepared-statements: true
  max-pool-prepared-statement-per-connection-size: 20
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  min-evictable-idle-time-millis: 300000
  validation-query: SELECT 1 FROM DUAL
  test-while-idle: true
  test-on-borrow: false
  test-on-return: false
  stat-view-servlet:
  enabled: true
  url-pattern: /monitor/druid/*
  filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  #图片上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 100Mb

ftp:
  userName: admin
  passWord: 123456
  address: 172.16.18.20
  port: 21
  basePath: /upload
  imageBasePath: http://172.16.18.20:8080/