spring:
  redis:
      database: 0
      hostName: 127.0.0.1
      port: 6379
      password: 123987       # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5
  datasource:
  #此处配置需要的数据源
#      username: ehc
      username: root
      password: msjkj
#      password: root
#      url: jdbc:oracle:thin:@172.16.18.88:1521:EHC
      url: jdbc:mysql://192.168.31.83:3306/div?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
#      driver-class-name: oracle.jdbc.OracleDriver
      driver-class-name: com.mysql.jdbc.Driver

  #图片上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 100Mb

#  http:
#    encoding:
#      force: true
#      charset: UTF-8
#      enabled: true
#      driver-class-name: com.mysql.jdbc.Driver

ftp:
  userName: sddz
  passWord: 123987
  address: 172.16.18.88
  port: 21
  basePath: /upload
  imageBasePath: http://172.16.18.88:9090/