spring:
#  redis:
#    database: 0
#    hostName: 127.0.0.1
#    port: 6379
#    password: 123987       # 密码（默认为空）
#    timeout: 6000  # 连接超时时长（毫秒）
#    pool:
#      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 10      # 连接池中的最大空闲连接
#      min-idle: 5
  datasource:
  #此处配置需要的数据源
      username: goods
#      username: root
      password: msj20181011
#      password: root
#      url: jdbc:oracle:thin:@172.16.10.66:1521:orcl
      url: jdbc:mysql://192.168.31.83:3306/meisijia?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
 #     driver-class-name: oracle.jdbc.OracleDriver
      driver-class-name: com.mysql.jdbc.Driver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true

 #图片上传
  servlet:
    multipart:
      enabled: true
      max-file-size: 10Mb
      max-request-size: 100Mb

ftp:
  userName: admin
  passWord: 123456
  address: 172.16.18.20
  port: 21
  basePath: /upload
  imageBasePath: http://172.16.18.20:8080/